version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py36jupyter
    platform: linux/amd64
    volumes:
      - "~:/src/notebooks/myfile"
    ports:
      - "8888:8888"
    tty: true
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
